### ISSUE TITLE
Can't find crate nalgebra

### ISSUE THREAD

**Issue by j4cobgarby** [sebcrozet/kiss3d#100]
Similar to another issue.
The fix for this was adding nalgebra as a dependency in my own project.

**Comment by sjaustirni** [comment]
I believe this issue should be closed as `nalgebra` [already is](https://github.com/sebcrozet/kiss3d/blob/304e339cd4d5492556c065aa41bdfcb6028e72d4/Cargo.toml#L32) a dependency for kiss3d.

**Comment by sebcrozet** [comment]
@j4cobgarby I'm closing this. Feel free to reopen and to provide more details about the issue if you encounter this issue again.
