### ISSUE TITLE
Pressing escape or exiting the program results in a panic

### ISSUE THREAD

**Issue by Candunc** [sebcrozet/kiss3d#101]
I'm using the spinning cube example from README.md, running Windows 10 x64 Version 1709, and I am using freetype271 from [this repository](https://github.com/ubawurinna/freetype-windows-binaries).

I have attached the error log: [stderr.txt](https://github.com/sebcrozet/kiss3d/files/1447388/stderr.txt)

**Comment by sebcrozet** [comment]
Fixed by #103 .
