### ISSUE TITLE
Update PointRenderer::draw_point() to allow setting point size

### ISSUE THREAD

**Issue by MattDerry** [sebcrozet/kiss3d#111]
Thanks for this great graphics module. I'm new to rust and I've been able to get up and running in no time.

I have a suggested enhancement that I wanted to document, which is to update the PointRendering API to allow for changing the rendered point size.

I believe this could be implemented at the application level or the shader level using glPointSize or gl_PointSize respectively.

**Comment by sebcrozet** [comment]
Thank you for your suggestion. That would be a great addition. Though I currently don't have the time to add this feature but that should be easy enough to add to the `PointRenderer`. Don't hesitate to submit a pull-request if you which to contribute!

**Comment by MattDerry** [comment]
Great, as I get a little better at understanding and writing idiomatic rust (I'm still in the semi-novice hacking stage of learning), I will see about making a PR. Thanks!

**Comment by MattDerry** [comment]
With [PR112](https://github.com/sebcrozet/kiss3d/pull/112) getting merged, I believe this issue can be closed.
