### ISSUE TITLE
Use nalgebra 0.15

### ISSUE THREAD

**Issue by OTL** [sebcrozet/kiss3d#114]
Hi, nalgebra 0.15 seems great.
I want to use nalgebra 0.15 with kiss3d.
If it uses v0.15, my projects will be cleaner than current situation (only kiss3d uses 0.14).

**Comment by sebcrozet** [comment]
Hi! I will be able to update the dependency on thursday.

**Comment by OTL** [comment]
Good news!! Thank you. Does it include update of ncollide?

**Comment by sebcrozet** [comment]
@OTL Kiss3d (version 0.15) and its ncollide3d (version 0.16) dependencies have been updated and published to cartes.io!

**Comment by OTL** [comment]
Thank you!
