### ISSUE TITLE
Points not rendering after update from kiss3d v0.13.0 to v0.14.0 

### ISSUE THREAD

**Issue by russmack** [sebcrozet/kiss3d#116]
The change from ncollide_procedural to ncollide3d in kiss3d v0.14.0 results in missing points.  Still looking into this but thought I'd put it out there in the meantime.

Here's a demo: https://gist.github.com/russmack/c1395fb3fbd6b16ea27dda722c582853

This is an issue on MacOS, not on Linux.

**Comment by sebcrozet** [comment]
Thank you for reporting this. This is fixed in kiss3d v0.16.
