### ISSUE TITLE
Processing input keys is broken

### ISSUE THREAD

**Issue by lain-dono** [sebcrozet/kiss3d#119]
https://github.com/sebcrozet/kiss3d/blob/280ed85fc6f5658f3514bf128bdfa88e892e60c1/src/window/gl_canvas.rs#L221
https://github.com/sebcrozet/kiss3d/blob/280ed85fc6f5658f3514bf128bdfa88e892e60c1/src/window/webgl_canvas.rs#L269

**Comment by sebcrozet** [comment]
Thanks for reporting this. Looks like a `sed` gone wrong.
