### ISSUE TITLE
Changing rotation (i.e. up-vector) of camera?

### ISSUE THREAD

**Issue by Andlon** [sebcrozet/kiss3d#122]
I cannot for the life of me figure out how to change the rotation of the camera. By rotation I mean rotation with respect to the direction the camera is pointing, i.e. changing the up vector, or, I think, the "roll" of the camera. Am I simply looking in the wrong places?

**Comment by sebcrozet** [comment]
The only way to change the up-vector is to define your own camera (implementing the [Camera](https://docs.rs/kiss3d/0.16.2/kiss3d/camera/trait.Camera.html) trait). Currently, both `ArcBall` and `FirstPerson` have an up-vector hard-coded to `y`. They could be modified to allow setting their up-vector to an arbitrary value but some care have to be taken regarding input handling.

**Comment by Andlon** [comment]
If I find the time, I might prepare a PR. Something like a `set_up(&mut self, up: Vector3<f32>)` method on the respective cameras?

(P.S: I find it strange that the default up-vector is not the z-axis. Wouldn't most people want to use z as the vertical axis in the world frame...?)

**Comment by sebcrozet** [comment]
Yup, `.set_up(...)` seems good, but taking the `Vector3` by reference.

I've always worked with the y axis as the "vertical" direction, and so did the few teams I've worked with so far. But I guess conventions differ depending on the field and on the people!

**Comment by JoshLambda** [comment]
Z-UP axis is becoming an industry standard. This is now the default on most design software excepted Maya and Unity.

Submitted PR #144. (Function to change up-axis. Default is still Y axis.)

**Comment by JoshLambda** [comment]
Z-UP is the new black.
Submitted a function to change up-axis in PR #145.

- Default is still Y axis. 
- Only changes First Person camera.
- Procedural objects are still pointing upward toward Y when generated.


Example:
```
let eye = Point3::new(20.0_f32, 20.0, #20.0);
let at = Point3::origin();
let mut first_person = FirstPerson::new(eye, at);
first_person.set_up_axis(Vector3::z());
```

**Comment by JoshLambda** [comment]
I submitted PR #146 with a function to change up-axis on Arc Ball camera.

**Important!** I didn't mention it in previous PR, but for both First Person and Arc Ball cameras, view only is affected, not camera movements. It means camera movements using keyboard/mouse are only consistent when using Y axis up.

As for First Person:
- Default is still Y axis up.
- Procedural objects are still pointing upward in Y direction when generated.
 
**Note: Making camera movements consistent with up-axis would require adding conditional statements in many functions, hence complexifying code source and increasing its length significantly. I'm not sure that's what you want in a KISS project.**

Usage example:

let eye = Point3::new(20.0_f32, 20.0,  20.0);
let at = Point3::origin();
let mut first_person = ArcBall::new(eye, at);
first_person.set_up_axis(Vector3::z());

**Comment by alvinhochun** [comment]
I'm trying to fix up the controls for the Arc Ball camera at least, but possibly also the First Person camera later. I only care for the right-handed Z-up case but I also want to do it properly for it to be merged, so there are a few questions that need to be answered:

1. Do we want to handle `set_up_axis(Vector3::x())`? Is there a use case? (I would expect no.)
2. How should `set_up_axis` behave if any other vectors are passed into it? (I would expect that it should panic, however doing this can be considered as a breaking change.)
