### ISSUE TITLE
Mesh::faces as Vec<Point3<u16>> is very limiting

### ISSUE THREAD

**Issue by TheStealthReporter** [sebcrozet/kiss3d#130]
`faces` in `kiss3d::resources::Mesh` is `u16`, which means only 65536 vertices can be addressed. This is very limiting for 3d objects. In previous revisions this was `i32` or `u32`. Was there a need to change/can it be reverted?

**Comment by sebcrozet** [comment]
The limitation to `u16` is required for compatibility with WebGL 1.0 (used when targeting WASM). This can't be reverted but a solution would be to add the ability to automatically split a big mesh into smaller pieces.

**Comment by OTL** [comment]
I have the same issue.
