### ISSUE TITLE
how to enable MSAA / multisampling?

### ISSUE THREAD

**Issue by sam0x17** [sebcrozet/kiss3d#177]
I know that normally one would do something like:
```
glfwWindowHint(GLFW_SAMPLES, 4);
glEnable(GL_MULTISAMPLE);
```

However my attempts to do this have failed. The closest I got is the following, which fails with "failed to create texture":

```
    unsafe {
        gl::Hint(gl::FRAMEBUFFER_DEFAULT_SAMPLES, 4);
        gl::Enable(gl::MULTISAMPLE);
    }
```

**Comment by MrRobb** [comment]
Any progress?

**Comment by sebcrozet** [comment]
Hi! I won't have time to address this issue for a while, though any PR would be appreciated in anyone else manages to get this working.
