### ISSUE TITLE
How to run examples?

### ISSUE THREAD

**Issue by ProkopHapala** [sebcrozet/kiss3d#188]
Everything seems to compile just fine, but I cannot find any binary to run in targets

I tried:
`/kiss3d/ci/build.sh`
`/kiss3d/> cargo build`

In both cases compilation finished without any erros

but when I go to `/kiss3d/target/debug/examples` it is empty

I cannot find anything about how to  run examples in the documentation

**Comment by sebcrozet** [comment]
Hi! The idiomatic way of running examples in rust is `cargo run --example cube`, where you can replace `cube` by the name of the example you want to run (i.e. the name of the `.rs` example file, but with out the extension).

**Comment by ProkopHapala** [comment]
Great! It works. Thanks.
