### ISSUE TITLE
Sidescroll camera has inverted view transform

### ISSUE THREAD

**Issue by MJohnson459** [sebcrozet/kiss3d#195]
I was using nphysics testbed which uses kiss3d under the hood to display some objects and the `look_at` method isn't doing what I expected (related issue https://github.com/rustsim/nphysics/issues/243#issue-540290375). In order to look at `(30,20)` for example I needed to call the method with negatives `(-30,-20)`. After a bit of digging it seems like the method is a straight pass through to the `Sidescroll` camera `look_at` method.

I think this line in the sidecroll.rs file:
```rust
    fn update_projviews(&mut self) {
        self.view = Translation2::new(self.at.x, self.at.y).to_homogeneous();
```
should actually be:
```rust
    fn update_projviews(&mut self) {
        self.view = Translation2::new(-self.at.x, -self.at.y).to_homogeneous();
```

https://github.com/sebcrozet/kiss3d/blob/cde25c321c1a3b824d08d7db6d803d252dc07f22/src/planar_camera/sidescroll.rs#L109

If that seems right I'm happy to create a PR for the change.

**Comment by sebcrozet** [comment]
You are right, there should be negative signs in there.

> If that seems right I'm happy to create a PR for the change.

That would be great!
