### ISSUE TITLE
Cube example build error on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by akiaji-k** [sebcrozet/kiss3d#200]
Hello,

I'm trying to build `kiss3d/example/*.rs` examples but it doesn't work well.
When I put a command like `bash$ cargo run --example cube`, I got an error message below.

> Compiling kiss3d v0.22.1 (/home/(user name)/rust_sources/kiss3d)
> error: linking with `cc` failed: exit code: 1
> 
>   = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/home/(user name)/.rustup/toolchains/1.37.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib"  ...(followed by long messages)
> 
>   = note: /home/(user name)/rust_sources/kiss3d/target/debug/deps/liblibloading-872b5e618dfa439b.rlib(libloading-872b5e618dfa439b.libloading.enoyblri-cgu.11.rcgu.o): In function `libloading::os::unix::DlerrorMutexGuard::new':
>           /home/(user name)/.cargo/registry/src/github.com-1ecc6299db9ec823/libloading-0.5.2/src/os/unix/mod.rs:18: undefined reference to `rust_libloading_dlerror_mutex_lock'
>           /home/(user name)/rust_sources/kiss3d/target/debug/deps/liblibloading-872b5e618dfa439b.rlib(libloading-872b5e618dfa439b.libloading.enoyblri-cgu.11.rcgu.o): In function `<libloading::os::unix::DlerrorMutexGuard as core::ops::drop::Drop>::drop':
>           /home/(user name)/.cargo/registry/src/github.com-1ecc6299db9ec823/libloading-0.5.2/src/os/unix/mod.rs:27: undefined reference to `rust_libloading_dlerror_mutex_unlock'
>           collect2: error: ld returned 1 exit status
>           
> 
> error: aborting due to previous error
> 
> error: Could not compile `kiss3d`.
> 
> 

It's happend on 
- Ubuntu 18.04 LTS 
- rustc v1.36/37/38/39/40.0 (`rust-toolchain` file was used)
- kiss3d v0.22.1, v21.0

environment.

Because there was `In function `libloading::os::unix::DlerrorMutexGuard::new':` in above error messages, I guessed Unix platform causes this problem.
So I tried same examples on 
- Windows10
- rustc v1.37/40.0 (`rust-toolchain` file was used)
- kiss3d v0.22.1 

then they worked well.

Is it caused by lack of any requirements for Unix or difference of platforms?
How do I fix this problem.

Thanks.

**Comment by sebcrozet** [comment]
Hi! This is odd. I'm running Ubuntu 19.10 and don't have this issue. So I guess there is something missing on your side. Do you have this problem only with kiss3d or with other projects as well?

Perhaps it could be worth asking this on the main Rust repository.

**Comment by akiaji-k** [comment]
Hi, sebcrozet
Thank you for your reply.

After when I read that you can build them on Ubuntu 19.10, I retried to build kiss3d/example codes on another (not used for above post) Ubuntu 18.04 LTS PC.
Then they are successfully run on environments below.

- Ubuntu 18.04 LTS
- rustc v1.36/37/38/40.0 (rust-toolchain file was used)
- kiss3d v0.22.1 (master repository)

But for rustc v1.38.0 I got same error messages in above post and failed to build.

I've not tested on the PC used for above post yet because I can't use it until 2 days later,  but it's probably enough to estimate that my environments cause this problem.
I will investigate how to fix them.

I'm writing some programs using kiss3d. It's so easy to use and fun to write.

I close this issue.

Thanks.
