### ISSUE TITLE
thread 'main' panicked at 'assertion failed: `(left == right)`

### ISSUE THREAD

**Issue by blooop** [sebcrozet/kiss3d#216]
Hi, 

I originally made this as an issue for URDF-VIZ but it looks like the error is coming from kiss3d and the author said he was not able to debug the problem at it works on his machine, but thinks it is related to OpenGL (Error code is 1281=0x501). 

Original issue:
https://github.com/OTL/urdf-viz/issues/30

**Summary of issue.**  
The render crashes immediately after opening and displays the error:

```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `1281`,
 right: `0`', /home/blooop/.cargo/registry/src/github.com-1ecc6299db9ec823/kiss3d-0.20.1/src/resource/framebuffer_manager.rs:55:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

This looks similar to the this issue:
https://github.com/sebcrozet/kiss3d/issues/131

Thanks

**Comment by bellwether-softworks** [comment]
I encounter this error if I attempt to perform consecutive renders, each with their own Window instance.  Consider the following process, which on the second pass of `main_sub` within the `window.render()` loop triggers the failure:

```rust
extern crate nalgebra as na;

use na::Point3;
use kiss3d::window::Window;

fn main() {
    main_sub();
    main_sub();
}

fn main_sub() {
    let mut window = Window::new("Window");

    let mut c = window.add_sphere(1.0);

    c.set_surface_rendering_activation(false);
    c.set_lines_color(Some(Point3::new(0.0, 1.0, 0.0)));
    c.set_lines_width(2.0);

    while window.render() {}
}
```
