### ISSUE TITLE
What's the difference between wgpu and kiss3d?

### ISSUE THREAD

**Issue by Joe23232** [sebcrozet/kiss3d#229]
Hi I am curious to know what is the difference between wgpu and kiss3d?

**Comment by alvinhochun** [comment]
This is like comparing apples to oranges. `wgpu` is an implementation of WebGPU, which provides a graphics API comparable to the likes of OpenGL, Vulkan, DirectX and Metal. `Kiss3d` is a graphics engine that handles projections, camera placements, simple shading, rendering of 2D and 3D primitives and 3D meshes, scene graphs and etc., and aims to provide a simple way of rendering a 3D scene without having to deal with a low-level graphics API directly.

**Comment by Joe23232** [comment]
Ah I see, thanks.
