### ISSUE TITLE
Unable to add custom shader attributes

### ISSUE THREAD

**Issue by G3ntIeMan** [sebcrozet/kiss3d#236]
Hi there! Recently I started using kiss3d for a tool and aims to visualize point clouds. Part of this process was keeping the points in memory so I needed to turn to a custom renderer. This worked fine until I wanted to add new input variables to the vertex shader, every time I try this `get_uniform` returns `None`. I am wondering what I am doing wrong here. 

An easy way to recreate what I am trying to do is to use the following patch on the latest master ([`f8dc9987`](https://github.com/sebcrozet/kiss3d/commit/f8dc99870eabb0f6918ba9fe7d0e39632d2272cb))

``` diff
diff --git a/src/renderer/point_renderer.rs b/src/renderer/point_renderer.rs
index 35caf6c2..d558c3f3 100644
--- a/src/renderer/point_renderer.rs
+++ b/src/renderer/point_renderer.rs
@@ -14,6 +14,7 @@ pub struct PointRenderer {
     shader: Effect,
     pos: ShaderAttribute<Point3<f32>>,
     color: ShaderAttribute<Point3<f32>>,
+    gamma: ShaderUniform<f32>,
     proj: ShaderUniform<Matrix4<f32>>,
     view: ShaderUniform<Matrix4<f32>>,
     points: GPUVec<Point3<f32>>,
@@ -31,6 +32,9 @@ impl PointRenderer {
             points: GPUVec::new(Vec::new(), BufferType::Array, AllocationType::StreamDraw),
             pos: shader.get_attrib::<Point3<f32>>("position").unwrap(),
             color: shader.get_attrib::<Point3<f32>>("color").unwrap(),
+            gamma: shader
+                .get_uniform::<f32>("gamma")
+                .expect("Could not retrieve uniform shader variable 'gamma'"),
             proj: shader.get_uniform::<Matrix4<f32>>("proj").unwrap(),
             view: shader.get_uniform::<Matrix4<f32>>("view").unwrap(),
             shader,
@@ -96,6 +100,7 @@ const A_VERY_LONG_STRING: &'static str = "#version 100
     attribute vec3 position;
     attribute vec3 color;
     varying   vec3 Color;
+    uniform   float gamma;
     uniform   mat4 proj;
     uniform   mat4 view;
     void main() {

```

and then run any example using the window, e.i. `cargo run --example lines`. You will always get `thread 'main' panicked at 'Could not retrieve uniform shader variable 'gamma'', src/renderer/point_renderer.rs:35:20`. Meaning that the program is unable to find the gamma variable, this is odd since I did add it to the shader.

 Hopefully somebody can give me a small nudge towards a solution, adding more inputs to the shaders would prove really useful!

**Comment by alvinhochun** [comment]
I suspect that would be due to the uniform being unused and optimized out by the shader compiler?

**Comment by G3ntIeMan** [comment]
@alvinhochun Many thanks! The uniform was seen as dead code and being dropped. I love it when the solution is simple.
