### ISSUE TITLE
set_point_size doesn't seem to change point size

### ISSUE THREAD

**Issue by yimmt** [sebcrozet/kiss3d#256]
I was running `example/points.rs`. I looked at the points and they looked super tiny, so I decided to change the size in `set_point_size` to something like 50, but the sizes looked the same when I ran it again (and with different numbers). It seems like something is broken, but I'm not sure if that is something on my end.

**Comment by sebcrozet** [comment]
Unfortunately, not all point sizes are supported by all graphics drivers. So maybe this is a limitation of your driver.
