### ISSUE TITLE
Master broken because of nalgebra version conflict

### ISSUE THREAD

**Issue by virtualritz** [sebcrozet/kiss3d#264]
master is broken because `kiss3d` depends on `nalgebra` `0.24.0` but it also depends on `ncollide3d` `0.26.1` which depends
on `nalgebra` `0.23.2`

```
Compiling kiss3d v0.28.0 (https://github.com/sebcrozet/kiss3d.git#9407e80a)
error[E0308]: mismatched types
  --> /Users/moritz/.cargo/git/checkouts/kiss3d-8d0a97ea1d6dd52e/9407e80/src/resource/mesh.rs:87:13
   |
87 |             coords,
   |             ^^^^^^ expected struct `na::Point`, found struct `ncollide3d::nalgebra::Point`
   |
   = note: expected struct `Vec<na::Point<f32, na::U3>>`
              found struct `Vec<ncollide3d::nalgebra::Point<f32, ncollide3d::nalgebra::U3>>`
   = note: perhaps two different versions of crate `nalgebra` are being used?
```

Basically, to use a recent `kiss3d` on `macOS` one now has to lock `Cargo.toml` to a commit tag 'somewhere' *after* #257 was fixed but *before* current master (current release, `0.28.0`, is broken on macOS (see #262)).

**Comment by sebcrozet** [comment]
I will probably make a new release of ncollide and kiss3d tomorrow. In the mean time, you can add this to your `Cargo.toml` to make it work again:
```rust
[patch.crates-io]
ncollide3d = { git = "https://github.com/dimforge/ncollide" }
ncollide2d = { git = "https://github.com/dimforge/ncollide" }
```

**Comment by virtualritz** [comment]
Thanks you!

**Comment by sebcrozet** [comment]
Kiss3D 0.29 has been released today.
