### ISSUE TITLE
set_points_size() does nothing

### ISSUE THREAD

**Issue by joseluis** [sebcrozet/kiss3d#271]
I was trying out the examples and it seems that changing the size value of a point doesn't have any effect at all, unlike changing a line's width which does work as expected.

**Comment by alvinhochun** [comment]
Please see #256, and explained by @sebcrozet:

> Unfortunately, not all point sizes are supported by all graphics drivers. So maybe this is a limitation of your driver.

**Comment by joseluis** [comment]
Thank you. I'm seeing it's [unimplemented in the gl context](https://github.com/sebcrozet/kiss3d/blob/master/src/context/gl_context.rs#L577), and [glow](https://docs.rs/glow/) doesn't seem to support it...

This unexpected behaviour I believe should be briefly indicated in the docs. I've just created a PR for that.
