### ISSUE TITLE
Questions regarding this project

### ISSUE THREAD

**Issue by Raj2032** [sebcrozet/kiss3d#291]
Hi I have some questions regarding this project:
1. Does this game engine support 2D sprites?
2. Does it use WGPU as its backend renderer or OpenGL or vulkan/vulkano?
3. Does it do asynchronous and multithreading?
4. Is there a GUI game editor (such as Godot etc) or perhaps a Blender extension?
5. How would performance compared to something such as [`bevy`](https://bevyengine.org/)?
6. Does it support my own created 3D models as well as animations/rigging?
7. Is there a Discord server (or something similar) for this game engine?
8. How well maintained is this game engine and how many people are currently contributing for it?
9. Is there support for egui backend renderer?

**Comment by alvinhochun** [comment]
Kiss3d is not a game engine, but rather a simple graphics library for drawing geometric shapes easily. It lacks the optimizations that game engines need. If you are looking to build a game, you probably want to look at rg3d or bevy instead.

**Comment by Raj2032** [comment]
Ok thanks mate
