### ISSUE TITLE
Text scale?

### ISSUE THREAD

**Issue by chlobes** [sebcrozet/kiss3d#292]
I'm trying to align text rendering with planar rendering, drawing some text on top of a rect to make a button for example.
But text rendering seems to use a different scale than pixels, the text appears much smaller than it should and offset up and left.
What determines text scale compared to pixel scale and how can I read or write it?

**Comment by Xtry15** [comment]
```
window.draw_text(
            &fps, 
            &Point2::origin(), 
            60.0, // **Scale**
            &Font::default(), 
            &Point3::new(0.6, 0.6, 1.0), );
```

**Comment by chlobes** [comment]
Yes, I am aware that is how you scale the text, however as I said the text __uses a different scale than pixels__, depending on the screen size, making drawing a simple button impossible. I have since moved on to libraries that support this.
