### ISSUE TITLE
Should the README use the bundled Nalgebra version?

### ISSUE THREAD

**Issue by TheCynosure** [sebcrozet/kiss3d#293]
The example on the README uses nalgebra as an external crate but when I ran this locally it complained of Kiss3d functions (particularly `from_axis_angle`) unable take Nalgebra objects but needed `kiss3d::nalgrebra` objects instead.

I think these lines in the README needs to be changed from:
```rust
extern create nalgebra as na;

use na::{Vector3, UnitQuaternion};
```
To
```rust
use kiss3d::nalgebra::{Vector3, UnitQuaternion};
```

Also just let me know if there is a way around this to use an external version of nalgebra that differs from the bundled version.

EDIT: I see this is acknowledged further down in the README, but if you are forced to used the same version of Nalgebra as Kiss3d anyways it might be easier for users to just use the bundled version.

**Comment by donkeyteethUX** [comment]
I'd approve a PR for this, if you want to make one. It's true that `nalgebra` compatibility issues are a pain point, particularly for users who want to use a different version.
