### ISSUE TITLE
Are there any plans on using wgpu?

### ISSUE THREAD

**Issue by Raj2032** [sebcrozet/kiss3d#300]
Hey guys I was curious if there were any plans on using wgpu?

**Comment by donkeyteethUX** [comment]
I personally don't have plans beyond providing maintenance and reviewing PRs. Out of curiosity, what particular benefits do you see in changing the backend to wgpu? Is there a particular platform you want to support?

**Comment by Raj2032** [comment]
@donkeyteethUX Isn't opengl not as performant as wgpu as wgpu can translate to vulkan which has more performance?

**Comment by donkeyteethUX** [comment]
Yeah vulkan would probably be more performant than opengl. Performance is already pretty decent for many use-cases, and optimal performance has never been a top priority of the project (elaborated in the README).
