### ISSUE TITLE
kiss3d performance

### ISSUE THREAD

**Issue by Xtry15** [sebcrozet/kiss3d#315]
Can I make game with kiss3d? In readme file, I read about the fact that kiss 3d was created for geometric 3d primitives. I want make simple, not hard game.

**Comment by donkeyteethUX** [comment]
Yes, you can certainly make a game with kiss3d. If you want a purpose-built game engine, however, I'd check out https://github.com/bevyengine/bevy.

**Comment by Xtry15** [comment]
Thank you! I know about bevy, but I want make my own engine, and with help my engine, make game. I want program yourself various thigs. For example phisics, collision and etc. I need only library for 3D rendering, but crates like wgpu, glium, miniquad, vulkano force me to write huge tons of code. With Kiss3D, I can render cube in two strings code. Thank you again!
