### ISSUE TITLE
seriousness of the library

### ISSUE THREAD

**Issue by ghost** [sebcrozet/kiss3d#316]
I want to make game engine based on this library. Library's license allows make it. Can I use kiss3d in 3D games? Not  a simple, but not a hard.

**Comment by n3vu0r** [comment]
Maintenance seems to be very passive. Its scene graph is not optimized for large numbers of nodes, I don't think it's well suited to use it as a base for a game engine. For games you definitely want to check out [Bevy Engine](https://bevyengine.org/) or [Fyrox](https://fyrox.rs/) and if you want to write your own engine, check out their dependencies instead.
