### ISSUE TITLE
Move `kiss3d_recording` to its own crate, or behind a cargo feature.

### ISSUE THREAD

**Issue by sebcrozet** [sebcrozet/kiss3d#44]

**Comment by wackywendell** [comment]
I moved it to its own crate: see [wackywendell/kiss3d_recording](https://github.com/wackywendell/kiss3d_recording).

It builds, and so does the example - but on my machine, I get some errors when I run the example:

```
$ ./target/debug/examples/recording
[mpeg @ 0x555612f53080] Using AVStream.codec.time_base as a timebase hint to the muxer is deprecated. Set AVStream.time_base instead.
[mpeg @ 0x555612f53080] VBV buffer size not set, using default size of 130KB
If you want the mpeg file to be compliant to some specification
Like DVD, VCD or others, make sure you set the correct buffer size
[swscaler @ 0x555612b17ec0] bad src image pointers
[swscaler @ 0x555612b17ec0] bad src image pointers
[swscaler @ 0x555612b17ec0] bad src image pointers
[swscaler @ 0x555612b17ec0] bad src image pointers
[swscaler @ 0x555612b17ec0] bad src image pointers
[swscaler @ 0x555612b17ec0] bad src image pointers
[...]
```

I would *love* some help, if you can spare it! Also, I'm happy to give/share that repository; its really mostly your code, and I just want it to work!

**Comment by sebcrozet** [comment]
I can't really clone anything this week because I currently have a very crappy internet connection, but as soon as I go back to my place I will take a look at this!

**Comment by wackywendell** [comment]
Great! Looking forward to it!

**Comment by sebcrozet** [comment]
Ok, so I cloned your repository and can reproduce the bug on my machine! I believe I found the origin of the `bad src image pointers` error. I'll open a PR with the fix on your repository. Let me know if this works on your system as well.

**Comment by wackywendell** [comment]
Alright!! It works on my system too! Thanks!

Moving forward: would you like to take over the `kiss3d_recording` repository? How would you like to proceed?

**Comment by sebcrozet** [comment]
I believe the simplest way of doing that, is that you transfer ownership of the repository (one of the red buttons on the bottom of the repository's `setting` page). I have never done that before so I don't know exactly what will happen (will it show up on may repository list?) but its worth a try!

**Comment by sebcrozet** [comment]
I believe the transfer worked. Thanks!
