### ISSUE TITLE
Unable to run the front page example

### ISSUE THREAD

**Issue by arno-lee** [sebcrozet/kiss3d#52]
When trying to fire up the first example got this:

$ cargo run
Compiling k3d_1 v0.1.0 
src/main.rs:17:37: 17:67 error: mismatched types:
 expected `&nalgebra::structs::vec::Vec3<f32>`,
    found `&nalgebra::structs::vec::Vec3<f32>`
(expected struct `nalgebra::structs::vec::Vec3`,
    found a different struct `nalgebra::structs::vec::Vec3`) [E0308]
src/main.rs:17         c.prepend_to_local_rotation(&Vec3::new(0.0f32, 0.014, 0.0));
                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/main.rs:17:37: 17:67 help: run `rustc --explain E0308` to see a detailed explanation
error: aborting due to previous error
Could not compile `k3d_1`.

$ cargo --version
cargo 0.4.0-nightly (89435c4 2015-07-01) (built 2015-06-30)
$ rustc --version
rustc 1.3.0-nightly (bf3c979ec 2015-06-30)

the same issue for the stable channel

**Comment by sebcrozet** [comment]
Could you show me your `Cargo.toml` file? It looks like the version of `nalgebra` you are using for the example is not the same as the one used by `kiss3d`.

**Comment by arno-lee** [comment]
it's quite basic, except for the stuff generated by default I only added

[dependencies.kiss3d]
git = "https://github.com/sebcrozet/kiss3d"

[dependencies.nalgebra]
git = "https://github.com/sebcrozet/nalgebra"

**Comment by sebcrozet** [comment]
Thanks!

I am pretty sure the errors come from the fact that you are using the github version of `nalgebra` while `kiss3d` depends on the version from `crates.io`. Two versions of the same libraries but coming from two different sources will make the compiler think they are different libraries (thus, the `Vec3` from the first version will be seen as a different thing as the `Vec3` from the second one) .

You should depend on the `crates.io` packages only. This can be done by replacing the git dependencies by:

```.toml
[dependencies]
nalgebra = "*"
kiss3d = "*"
```

**Comment by arno-lee** [comment]
ok, thank you for explanation!
