### ISSUE TITLE
regenerate online documentation

### ISSUE THREAD

**Issue by durka** [sebcrozet/kiss3d#63]
At least the example in the online docs is out of date (`extern crate native` etc) and doesn't seem to match the doc comments in src/lib.rs

**Comment by Phrohdoh** [comment]
@sebcrozet I've generated documentation based off of https://github.com/Phrohdoh/kiss3d/commit/8ef5c724a48a64f3c75197e62e0bce9ce7350268 but I cannot figure out how to submit documentation for the `gh-pages` branch.

How should I go about this?

**Comment by sebcrozet** [comment]
I’m not sure but doesn't github let you select the branch you which to create a PR on ?

**Comment by Phrohdoh** [comment]
It does, but even when I checkout `gh-pages` `target/docs` is ignored for some reason, even though the `.gitignore` is different.

I'm not sure what the issue here is.
