### ISSUE TITLE
window.rs:327:38: 327:67 error: mismatched types: expected `*const std::os::raw::c_void`, found `*const libc::c_void`

### ISSUE THREAD

**Issue by MrAndMrsK** [sebcrozet/kiss3d#68]
When attempting to build the readme sample (and installing opengl `freeglut3-dev`, and randr `xorg-dev libglu1-mesa-dev`) I'm getting this:

``` text
Executing: cargo build 
   Compiling kiss3d v0.1.4 (https://github.com/sebcrozet/kiss3d#98f00870)
~/.cargo/git/checkouts/kiss3d-fdfcc5cc23d2dd9f/master/src/window/window.rs:327:38: 327:67 error: mismatched types:
 expected `*const std::os::raw::c_void`,
    found `*const libc::c_void`
(expected enum `std::os::raw::c_void`,
    found enum `libc::c_void`) [E0308]
~/.cargo/git/checkouts/kiss3d-fdfcc5cc23d2dd9f/master/src/window/window.rs:327         verify!(gl::load_with(|name| window.get_proc_address(name)));
                                                                                                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~/.cargo/git/checkouts/kiss3d-fdfcc5cc23d2dd9f/master/src/window/window.rs:327:9: 327:70 note: in this expansion of verify! (defined in ~/.cargo/git/checkouts/kiss3d-fdfcc5cc23d2dd9f/master/src/error.rs)
~/.cargo/git/checkouts/kiss3d-fdfcc5cc23d2dd9f/master/src/window/window.rs:327:38: 327:67 help: run `rustc --explain E0308` to see a detailed explanation
error: aborting due to previous error
Could not compile `kiss3d`.
```

The readme says that the latest nightlies of rust are required, but that was edited a long time ago so is that still necessary?

**Comment by MrAndMrsK** [comment]
I commented out the `verify!` line because to me it seemed like a somewhat optional `assert` kind of statement.  That let it keep going but I still had errors with an ambiguous `Vec3` in the sample which I changed to `&na::Vec3::new...` instead.  

Now it builds through but at runtime I get `thread '<main>' panicked at 'gl function was not loaded', ~/Projects/hello_world/target/debug/build/gl-f2eae2a83ed0cb03/out/bindings.rs:23202`

**Comment by MrAndMrsK** [comment]
I also tried removing those glut packages and installed glew instead but I get the same result.

**Comment by Ticki** [comment]
> The readme says that the latest nightlies of rust are required, but that was edited a long time ago so is that still necessary?

Doesn't compile on latest (today's) nightlies.

**Comment by Ticki** [comment]
It works when doing transmute.

**Comment by Ticki** [comment]
Fixed by #70

**Comment by bjz** [comment]
This is due to the latest updates in gl-rs. glfw seems to be behind. Could you look into this @bvssvni?

**Comment by bvssvni** [comment]
@bjz Looking. I ran into some minor issues that we might want to check first. https://github.com/PistonDevelopers/glfw-sys/issues/5, https://github.com/PistonDevelopers/glfw-sys/issues/6, https://github.com/PistonDevelopers/glfw-rs/issues/331.
