### ISSUE TITLE
Example on kiss3d.org does not compile

### ISSUE THREAD

**Issue by nicholasbishop** [sebcrozet/kiss3d#75]
It also does not match the example in the readme.

**Comment by lunarpulse** [comment]
The same problem here

see the details below
Build failed, waiting for other jobs to finish...
error: failed to run custom build command for `glfw-sys v3.1.3`
process didn't exit successfully: `/home/########/Documents/Github/RustC/kiss3d/target/debug/build/glfw-sys-fd61b00ae1885d6f/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Failed to execute cmake: No such file or directory (os error 2)', /home/######/.cargo/registry/src/github.com-1ecc6299db9ec823/glfw-sys-3.1.3/build.rs:15
note: Run with `RUST_BACKTRACE=1` for a backtrace.

**Comment by rebo** [comment]
I get this error as well

**Comment by sebcrozet** [comment]
It looks like you need to install cmake in order to compile glfw-sys.

**Comment by unpatched** [comment]
I was missing a few deps besides cmake in case somebody else comes across this issue.

`apt-get install cmake xorg-dev libglu1-mesa-dev`

I'm not sure which fixed the error, but I can run the examples now.

**Comment by martinlindhe** [comment]
A working example is https://github.com/sebcrozet/kiss3d/blob/master/examples/cube.rs

both the README.md and the red rotating cube example on kiss3d.org is outdated
