### ISSUE TITLE
Can't Build on Windows

### ISSUE THREAD

**Issue by hywei** [sebcrozet/kiss3d#81]
After run `cargo build` on cmd:

error: failed to run custom build command for `glfw-sys v3.1.3`

CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
', D:\workspace\.cargo\registry\src\github.com-88ac128001ac3a9a\glfw-sys-3.1.3\build.rs:18

**Comment by sebcrozet** [comment]
There is probably an issue with you glfw setup. In particular, you have to install glfw (the C library) separately. Perhaps you could try to follow the hints from the readme of [glfw-rs](https://github.com/PistonDevelopers/glfw-rs)  and attempt to compile their example.

Also you may try to modify the glfw dependency of `kiss3d` to disable the default features as suggested on the glfw-rs readme:

```toml
[dependencies.glfw]
version = "0.2.*"
default-features = false
```

**Comment by hywei** [comment]
@sebcrozet This works, thanks!

**Comment by ChristianBeilschmidt** [comment]
@hywei I'm not quite sure how you've got this to work. This solution does not work for me out of the box. Can you please give some details on the fix?

How does your glfw setup look like?
