### ISSUE TITLE
Docs refer to Pnt3, Vec3 but nalgebra renamed to Point3, Vector3, etc.

### ISSUE THREAD

**Issue by barbeque** [sebcrozet/kiss3d#91]
I noticed that in the example code, it has already been changed.

I tried forking the repo and editing the gh-pages branch manually but it looks like it is automatically generated somehow - if you could please offer some guidance on how to modify the documentation to be up to date, I would love to help.

It's a great and easy library to get up and running with - much simpler than most C++ ones I've seen.

If it matters, my Cargo.toml is:

```
[dependencies]
nalgebra = "*"

[dependencies.kiss3d]
git = "https://github.com/sebcrozet/kiss3d"
```

It pulled nalgebra v0.11.2 from crates.io

**Comment by sebcrozet** [comment]
The documentation is automatically generated by rustdoc. Its content is copied to the [doc](https://github.com/sebcrozet/kiss3d/tree/gh-pages/doc) folder on the `gh-pages` branch. So you may run `cargo doc --no-deps` and copy the content of `kiss3d/target/doc`.

But I have a script that does just that automatically. I just have to run it now and it will be done!

**Comment by sebcrozet** [comment]
It should be up to date now!
